[project]
name = "w1-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.140.0",
    "httpx>=0.28.1",
    "openai>=2.48.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "tiktoken>=0.13.0",
    "uvicorn>=0.51.0",
]
